### ISSUE TITLE
[Bug]: python3 manage.py migrate issue

### ISSUE THREAD

**Issue by acentoz** [Onemind-Services-LLC/netbox-metatype-importer#16]
### NetBox plugin version

v0.0.4

### NetBox version

v3.4.9

### Steps to Reproduce

python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.4.9/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.4.9/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/netbox-3.4.9/venv/lib64/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox-3.4.9/venv/lib64/python3.8/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/netbox-3.4.9/netbox/extras/plugins/__init__.py", line 105, in ready
    register_template_extensions(template_extensions)
  File "/opt/netbox-3.4.9/netbox/extras/plugins/registration.py", line 21, in register_template_extensions
    for template_extension in class_list:
TypeError: 'NoneType' object is not iterable

### Expected Behavior

Importer OK.

### Observed Behavior

Not working.

**Comment by abhi1693** [comment]
I'm unable to reproduce this issue

```
(venv) ➜  netbox git:(v3.4.9) python manage.py migrate                                                                                                                                                     git:(v3.4.9|) 
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_metatype_importer, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying netbox_metatype_importer.0001_initial... OK
(venv) ➜  netbox git:(v3.4.9)   
```
